analytics: {}
color:
  brandColors:
    - '#7A1712'
    - '#C3D8E9'
    - '#D64D2D'
    - '#DA7934'
    - '#161010'
  brandStrength: 0.156531
  lightness: 0.283783
  rhythmicContrast: 0.195945
  saturation: 0.318693
cta: {}
layout_spectrum: 0.600225
name: 'Travel over Egypt '
opengraph: {}
purpose: {}
typography_spectrum: 0.987612
