analytics: {}
color:
  brandColors:
    - '#FEFEFE'
    - '#F2940C'
    - '#2EA7E0'
    - '#F7C518'
    - '#F7E01E'
  brandStrength: 0.156531
  lightness: 0.283783
  rhythmicContrast: 0.195945
  saturation: 0.318693
cta: {}
layout_spectrum: 0.600225
name: 'Travel over Egypt '
opengraph: {}
purpose: {}
typography_spectrum: 0.987612
