analytics: {}
color:
  brandColors:
    - '#000000'
    - '#683008'
    - '#706850'
    - '#F0B018'
    - '#F0E880'
  brandStrength: 0.335585
  lightness: 0.509009
  rhythmicContrast: 0.240991
  saturation: 0.492117
cta: {}
layout_spectrum: 0.793918
name: 'Travel over Egypt '
opengraph: {}
purpose: {}
typography_spectrum: 0.994369
