name: 'http//:traveloveregypt.com '
favicon: null
layout_spectrum: 0.600225
typography_spectrum: 0.987612
title: TRAVEL OVER EGYPT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090506'
    - '#8B3600'
    - '#FD8344'
    - '#FCE36D'
    - '#B06136'
  brandStrength: 0.156531
  lightness: 0.283783
  saturation: 0.318693
  rhythmicContrast: 0.195945
purpose:
  - name: null
    item: null
    url: null
