analytics: {}
color:
  brandColors:
    - '#C0C8D0'
    - '#205880'
    - '#8090A0'
    - '#F0A040'
    - '#D8C8A8'
  brandStrength: 0.320945
  lightness: 0.68018
  rhythmicContrast: 0.694819
  saturation: 0.497747
cta: {}
layout_spectrum: 0.396396
name: 'Travel over Egypt '
opengraph: {}
purpose: {}
typography_spectrum: 0.385135
