analytics: {}
color:
  brandColors:
    - '#C0C8D0'
    - '#205880'
    - '#8090A0'
    - '#F0A040'
    - '#D8C8A8'
  brandStrength: 0.314189
  lightness: 0.68018
  rhythmicContrast: 0.673423
  saturation: 0.653153
cta: {}
layout_spectrum: 0.524774
name: 'Travel over Egypt '
opengraph: {}
purpose: {}
typography_spectrum: 0.994369
