name: 'http//:traveloveregypt.com '
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/00f0b57f-e905-4e23-b037-010990210ce1.jpg
layout_spectrum: 1
typography_spectrum: 1
cta: {}
analytics:
  facebook: ''
  google: UA-80814309-1
  twitter: ''
opengraph:
  type: ''
  appId: 'traveloveregypt '
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/25ba5e28-5d52-4293-b808-9c0e9148ee45.jpg
color:
  brandColors:
    - '#F8F9FC'
    - '#224FAA'
    - '#A62626'
    - '#3D588F'
    - '#C7CAD1'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose:
  - type: contact
    label: Email us
    url: 'mailto:info@traveloveregypt.com'
  - type: contact
    label: 'Call us:+201100542030'
    url: 'tel:+201100542030'
title: TRAVEL OVER EGYPT
description: 'Tours,accommodation all over Egypt & beyond '
author:
  url: 'http://traveloveregypt.com'
  email: info@traveloveregypt.com
content_rating:
  adult: false
navigation:
  - name: 'The best air ticket prices from Qtarairway '
    url: 'http://qatarairways.go2cloud.org/aff_c?offer_id=2&aff_id=4005'
    type: external
  - name: 'Three corners sea beach resort,Marsa Alam'
    id: a7bc3779-3bc5-4c51-9c1d-47e011837e30
    type: content
  - name: Three corners Equinox resort
    id: efe60fb8-2c6c-47f2-80ec-a4a226954ad6
    type: content
  - name: 'Tia Heights resort,Hurghada'
    id: e55ca1e9-0d2a-47d5-8cf2-1093755f6651
    type: content
  - name: 'Dahabiya Nile cruise '
    id: 81275e91-0459-4458-85b0-4a13ad53a5df
    type: content
  - name: Queen Nefertari
    id: e3d5f486-38c2-4831-9fa2-c7dac5bc3743
    type: content
  - name: 'The temples of Abu Simbel. '
    id: b26103f8-693c-4c69-afbc-2baabecb0972
    type: content
  - name: 'Tour Packages:'
    id: 53463c40-5c5c-44ae-bba3-28293ed9401d
    type: content
  - name: 'M/S Blue Shadow:'
    id: 64273065-fbad-4d11-80b4-c7d17b9b5541
    type: content
  - name: 'About us..... '
    id: 6746b321-5f93-42ac-8c34-20fb6c38f96b
    type: content
content: []
github: true
