layout_spectrum: 0.9386220665182918
typography_spectrum: 0.2343213518615812
color:
  brandColors:
    - '#090506'
    - '#8B3600'
    - '#FD8344'
    - '#FCE36D'
    - '#B06136'
  brandStrength: 0.9390193459112197
  lightness: 0.42593582486733794
  saturation: 0.8454341206233948
  rhythmicContrast: 0.1924311297480017
coverPrefs:
  filter: false
name: 'http//:traveloveregypt.com '
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/00f0b57f-e905-4e23-b037-010990210ce1.jpg
cta: {}
analytics:
  facebook: ''
  google: UA-80814309-1
  twitter: ''
opengraph:
  type: ''
  appId: ''
purpose: []
title: TRAVEL OVER EGYPT
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
