layout_spectrum: 0.7981968112289906
typography_spectrum: 0.37979158316738904
color:
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  brandStrength: 0.8560164058580995
  lightness: 0.8351110115181655
  saturation: 0.05724932160228491
  rhythmicContrast: 0.189755751285702
coverPrefs:
  filter: false
name: 'http//:traveloveregypt.com '
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/00f0b57f-e905-4e23-b037-010990210ce1.jpg
cta: {}
analytics:
  facebook: ''
  google: UA-80814309-1
  twitter: ''
opengraph:
  type: ''
  appId: ''
purpose: []
title: TRAVEL OVER EGYPT
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
