analytics: {}
color:
  brandColors:
    - '#E3E0DB'
    - '#79ACC1'
    - '#2A2B25'
    - '#756653'
    - '#988E6B'
  brandStrength: 0.156531
  lightness: 0.283783
  rhythmicContrast: 0.195945
  saturation: 0.318693
cta: {}
layout_spectrum: 0.600225
name: 'Travel over Egypt '
opengraph: {}
purpose: {}
typography_spectrum: 0.987612
