analytics: {}
color:
  brandColors:
    - '#090506'
    - '#8B3600'
    - '#FD8344'
    - '#FCE36D'
    - '#B06136'
  brandStrength: 0.156531
  lightness: 0.283783
  rhythmicContrast: 0.195945
  saturation: 0.318693
cta: {}
layout_spectrum: 0.600225
name: 'http//:travelalloveregypt.com'
opengraph: {}
purpose: {}
typography_spectrum: 0.987612
