layout_spectrum: 0.5644163677934557
typography_spectrum: 0.5263351022731513
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.7303197248838842
  lightness: 0.7451995483133942
  saturation: 0.03939730883575976
  rhythmicContrast: 0.2793304461520165
coverPrefs:
  filter: false
name: 'http//:traveloveregypt.com '
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/00f0b57f-e905-4e23-b037-010990210ce1.jpg
cta: {}
analytics:
  facebook: ''
  google: UA-80814309-1
  twitter: ''
opengraph:
  type: ''
  appId: ''
purpose: []
title: TRAVEL OVER EGYPT
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
