analytics: {}
color:
  brandColors:
    - '#C0C8D0'
    - '#205880'
    - '#8090A0'
    - '#F0A040'
    - '#D8C8A8'
  brandStrength: 0.644144
  lightness: 0.509009
  rhythmicContrast: 0.489864
  saturation: 0.492117
cta: {}
layout_spectrum: 0.524774
name: 'Travel over Egypt '
opengraph: {}
purpose: {}
typography_spectrum: 0.994369
