name: 'http//:traveloveregypt.com '
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/00f0b57f-e905-4e23-b037-010990210ce1.jpg
layout_spectrum: 0.8940469026760115
typography_spectrum: 0.5069132497128431
cta: {}
analytics:
  facebook: www.facebook.com/traveloveregypt
  google: UA-80814309-1
  twitter: ''
opengraph:
  type: ''
  appId: 'traveloveregypt '
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/25ba5e28-5d52-4293-b808-9c0e9148ee45.jpg
color:
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  brandStrength: 0.1762378474262239
  lightness: 0.30299579117188946
  saturation: 0.3593283181535172
  rhythmicContrast: 0.12104018753754103
purpose:
  - type: contact
    label: Email us
    url: 'mailto:info@traveloveregypt.com'
  - type: contact
    label: 'Call us:+201100542030'
    url: 'tel:+201100542030'
title: TRAVEL OVER EGYPT
description: 'Tours,accommodation all over Egypt & beyond '
author:
  url: 'http://traveloveregypt.com'
  email: info@traveloveregypt.com
content_rating:
  adult: false
navigation:
  - name: 'The best air ticket prices from Qtarairway '
    url: 'http://qatarairways.go2cloud.org/aff_c?offer_id=2&aff_id=4005'
    type: external
  - name: 'Three corners sea beach resort,Marsa Alam'
    id: a7bc3779-3bc5-4c51-9c1d-47e011837e30
    type: content
  - name: 'Three Corners Happy Life:'
    id: 7e2d538b-2df2-431a-ac52-fef90cda41df
    type: content
  - name: Three corners Equinox resort
    id: efe60fb8-2c6c-47f2-80ec-a4a226954ad6
    type: content
  - name: 'Three Corners Fairouz Plaza:'
    id: 97c3cb83-9392-4f83-9800-3388d365662a
    type: content
  - name: 'Novotel Marsa Allam:'
    id: 04c264eb-7c64-4970-9423-2cedadae5241
    type: content
  - name: 'Three Corners Sunny beach,Hurghada:'
    id: 0d14aa97-4856-4af7-b5cc-8a75a678ce67
    type: content
  - name: 'Three Corners Royal Star,Hurghada:'
    id: 6106e9a1-291f-4c30-b4d3-2a5a35e5e8a7
    type: content
  - name: 'Labranda Royal Makady:'
    id: 1f46b6b7-da7b-4946-bb8c-998d87245d4d
    type: content
  - name: 'Labranda Garden Makady:'
    id: 063e3e7c-2769-4b9b-984a-ab6aca3842be
    type: content
  - name: 'Labranda Club Makady:'
    id: 9292a177-9abc-4bc0-a9a7-fd324c8a2341
    type: content
  - name: 'Tia Heights resort,Hurghada'
    id: e55ca1e9-0d2a-47d5-8cf2-1093755f6651
    type: content
  - name: 'Tour Packages:'
    id: 53463c40-5c5c-44ae-bba3-28293ed9401d
    type: content
  - name: 'M/S Blue Shadow:'
    id: 64273065-fbad-4d11-80b4-c7d17b9b5541
    type: content
  - name: 'Dahabiya Nile cruise '
    id: 81275e91-0459-4458-85b0-4a13ad53a5df
    type: content
  - name: 'Tour Packages:'
    id: 53463c40-5c5c-44ae-bba3-28293ed9401d
    type: content
  - name: Queen Nefertari
    id: e3d5f486-38c2-4831-9fa2-c7dac5bc3743
    type: content
  - name: 'The temples of Abu Simbel. '
    id: b26103f8-693c-4c69-afbc-2baabecb0972
    type: content
  - name: 'About us..... '
    id: 6746b321-5f93-42ac-8c34-20fb6c38f96b
    type: content
  - name: 'Three Corners Rihanna Resort,El-Gouna:'
    id: 6ecc80c3-0f83-414c-be01-8290473fe69c
    type: content
content: []
github: true
