layout_spectrum: 0.58664
typography_spectrum: 0.24137940723448992
color:
  brandColors:
    - '#090506'
    - '#8B3600'
    - '#FD8344'
    - '#FCE36D'
    - '#B06136'
  brandStrength: 0.0625
  lightness: 0.125
  saturation: 0
  rhythmicContrast: 0.25
coverPrefs:
  filter: false
name: 'http//:traveloveregypt.com '
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/00f0b57f-e905-4e23-b037-010990210ce1.jpg
cta: {}
analytics:
  facebook: ''
  google: UA-80814309-1
  twitter: ''
opengraph:
  type: ''
  appId: ''
purpose: []
title: TRAVEL OVER EGYPT
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
