name: 'http//:traveloveregypt.com '
layout_spectrum: 0.58664
typography_spectrum: 1
cta: {}
analytics:
  facebook: ''
  google: UA-80814309-1
  twitter: ''
opengraph: {}
color:
  brandColors:
    - '#090506'
    - '#8B3600'
    - '#FD8344'
    - '#FCE36D'
    - '#B06136'
  brandStrength: 0.0625
  lightness: 0.125
  saturation: 0
  rhythmicContrast: 0.25
purpose:
  - {}
title: TRAVEL OVER EGYPT
